# Generated by Django 5.0.14 on 2026-02-27 23:08

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('pickup_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('pickup_address', models.CharField(blank=True, max_length=255)),
                ('customer_soc_percent', models.PositiveIntegerField(default=10)),
                ('est_kwh_needed', models.DecimalField(decimal_places=2, default=12.0, max_digits=6)),
                ('status', models.CharField(choices=[('REQUESTED', 'Requested'), ('DISPATCHING', 'Dispatching'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('CHARGING', 'Charging'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], default='REQUESTED', max_length=20)),
                ('eta_minutes', models.PositiveIntegerField(default=45)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_vehicle', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.vehicleunit')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='jobs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(max_length=40)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('meta', models.JSONField(blank=True, default=dict)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='dispatch.job')),
            ],
        ),
        migrations.CreateModel(
            name='JobOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], default='PENDING', max_length=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='dispatch.job')),
                ('vehicle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='fleet.vehicleunit')),
            ],
            options={
                'unique_together': {('job', 'vehicle_unit')},
            },
        ),
    ]
