# Generated by Django 5.0.14 on 2026-03-01 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0002_job_idempotency_key_job_idempotency_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='joboffer',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
