# Generated by Django 5.0.14 on 2026-03-05 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0003_joboffer_expires_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='driver_last_ping_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='driver_lng',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
