# Generated by Django 5.0.14 on 2026-03-08 21:43

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dispatch', '0004_job_driver_last_ping_at_job_driver_lat_and_more'),
        ('fleet', '0003_alter_vehicleunit_lat_alter_vehicleunit_lng'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobevent',
            options={'ordering': ['at']},
        ),
        migrations.AlterModelOptions(
            name='joboffer',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterUniqueTogether(
            name='joboffer',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='job',
            name='assigned_vehicle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_jobs', to='fleet.vehicleunit'),
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('REQUESTED', 'Requested'), ('DISPATCHING', 'Dispatching'), ('ASSIGNED', 'Assigned'), ('EN_ROUTE', 'En Route'), ('ARRIVED', 'Arrived'), ('CHARGING', 'Charging'), ('COMPLETED', 'Completed'), ('CANCELED', 'Canceled')], db_index=True, default='REQUESTED', max_length=20),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='created_at',
            field=models.DateTimeField(db_index=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='joboffer',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('ACCEPTED', 'Accepted'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired')], db_index=True, default='PENDING', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='joboffer',
            constraint=models.UniqueConstraint(fields=('job', 'vehicle_unit'), name='uniq_offer_per_job_vehicle_unit'),
        ),
    ]
