# Generated by Django 5.0.14 on 2026-02-27 23:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VehicleUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50, unique=True)),
                ('operator_type', models.CharField(choices=[('COMPANY', 'Company'), ('INDEPENDENT', 'Independent')], default='COMPANY', max_length=20)),
                ('lat', models.DecimalField(decimal_places=6, default=38.9072, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, default=-77.0369, max_digits=9)),
                ('battery_percent', models.PositiveIntegerField(default=90)),
                ('is_active', models.BooleanField(default=True)),
                ('operator', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicle_units', to=settings.AUTH_USER_MODEL)),
                ('zone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='fleet.servicezone')),
            ],
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.DateTimeField(default=django.utils.timezone.now)),
                ('end', models.DateTimeField(blank=True, null=True)),
                ('on_duty', models.BooleanField(default=True)),
                ('vehicle_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shifts', to='fleet.vehicleunit')),
            ],
        ),
    ]
