# Generated by Django 5.0.14 on 2026-03-08 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleunit',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
