# Generated by Django 5.0.14 on 2026-03-08 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fleet', '0002_vehicleunit_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicleunit',
            name='lat',
            field=models.DecimalField(db_index=True, decimal_places=6, default=38.9072, max_digits=9),
        ),
        migrations.AlterField(
            model_name='vehicleunit',
            name='lng',
            field=models.DecimalField(db_index=True, decimal_places=6, default=-77.0369, max_digits=9),
        ),
    ]
